[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10536be30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ba307ea90b9403c6035df7f2f6f85dce/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105368830>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ba307ea90b9403c6035df7f2f6f85dce/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10536b590>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ba307ea90b9403c6035df7f2f6f85dce/url